// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAPI.Data;

#nullable disable

namespace MyAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("MyAPI.Data.Banner", b =>
                {
                    b.Property<string>("MaBanner")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenBanner")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaBanner")
                        .HasName("PRIMARY");

                    b.ToTable("banner", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.Binhluan", b =>
                {
                    b.Property<string>("MaBl")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MaBL");

                    b.Property<string>("MaKh")
                        .HasColumnType("longtext");

                    b.Property<string>("MaKich")
                        .HasColumnType("longtext");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaBl")
                        .HasName("PRIMARY");

                    b.ToTable("binhluan", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.Daodien", b =>
                {
                    b.Property<string>("MaDaoDien")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaNhaKich")
                        .HasColumnType("longtext");

                    b.Property<string>("TenDaoDien")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaDaoDien")
                        .HasName("PRIMARY");

                    b.ToTable("daodien", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.Dienvien", b =>
                {
                    b.Property<string>("MaDienVien")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaNhaKich")
                        .HasColumnType("longtext");

                    b.Property<string>("TenDienVien")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaDienVien")
                        .HasName("PRIMARY");

                    b.ToTable("dienvien", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.Ghe", b =>
                {
                    b.Property<string>("MaGhe")
                        .HasColumnType("varchar(255)");

                    b.Property<float?>("GiaGhe")
                        .HasColumnType("float");

                    b.Property<string>("Hang")
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)");

                    b.Property<string>("NhaKich")
                        .HasColumnType("longtext");

                    b.Property<int?>("Seat")
                        .HasColumnType("int");

                    b.Property<string>("TenGhe")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<ulong?>("TinhTrangGhe")
                        .HasColumnType("bit(1)");

                    b.HasKey("MaGhe")
                        .HasName("PRIMARY");

                    b.ToTable("ghe", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.Khachhang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Avarta")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenKh")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TenKH");

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaKh")
                        .HasName("PRIMARY");

                    b.ToTable("khachhang", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.Khuyenmai", b =>
                {
                    b.Property<string>("MaKm")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MaKM");

                    b.Property<string>("ChuDe")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaKich")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayBd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayBD");

                    b.Property<DateTime?>("NgayKt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayKT");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaKm")
                        .HasName("PRIMARY");

                    b.ToTable("khuyenmai", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.Kich", b =>
                {
                    b.Property<string>("MaKich")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DaoDien")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DienVien")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaNhaKich")
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayBd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayBD");

                    b.Property<DateTime?>("NgayKt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayKT");

                    b.Property<string>("TenKich")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TheLoai")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<ulong?>("TrangThai")
                        .HasColumnType("bit(1)");

                    b.HasKey("MaKich")
                        .HasName("PRIMARY");

                    b.ToTable("kich", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.KichDienvien", b =>
                {
                    b.Property<string>("MaDienVien")
                        .HasColumnType("longtext");

                    b.Property<string>("MaKich")
                        .HasColumnType("longtext");

                    b.ToTable("kich_dienvien", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.Lichchieu", b =>
                {
                    b.Property<string>("MaLichChieu")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("NgayBd")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayBD");

                    b.Property<DateTime?>("NgayKt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("NgayKT");

                    b.HasKey("MaLichChieu")
                        .HasName("PRIMARY");

                    b.ToTable("lichchieu", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.Nhakich", b =>
                {
                    b.Property<string>("MaNhaKich")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TenNhaKich")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaNhaKich")
                        .HasName("PRIMARY");

                    b.ToTable("nhakich", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.Taikhoan", b =>
                {
                    b.Property<string>("MaTk")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Email")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("LoaiTaiKhoan")
                        .HasMaxLength(225)
                        .HasColumnType("varchar(225)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("SDT");

                    b.Property<string>("TenTaiKhoan")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaTk")
                        .HasName("PRIMARY");

                    b.ToTable("taikhoan", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.Ve", b =>
                {
                    b.Property<string>("MaVe")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MaGhe")
                        .HasColumnType("longtext");

                    b.Property<string>("MaKh")
                        .HasColumnType("longtext");

                    b.Property<string>("MaTk")
                        .HasColumnType("longtext");

                    b.Property<string>("MaXc")
                        .HasColumnType("longtext")
                        .HasColumnName("MaXC");

                    b.Property<DateTime?>("NgayDatVe")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<float?>("TongGia")
                        .HasColumnType("float");

                    b.HasKey("MaVe")
                        .HasName("PRIMARY");

                    b.ToTable("ve", (string)null);
                });

            modelBuilder.Entity("MyAPI.Data.Xuatchieu", b =>
                {
                    b.Property<string>("MaXc")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MaXC");

                    b.Property<string>("MaKich")
                        .HasColumnType("longtext");

                    b.Property<string>("MaLichChieu")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("NgayGio")
                        .HasColumnType("datetime(6)");

                    b.HasKey("MaXc")
                        .HasName("PRIMARY");

                    b.ToTable("xuatchieu", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
